# Config file for DeepForest pytorch module

#cpu workers for data loaders
#Dataloaders
workers: 5
accelerator: auto
batch_size: 8
devices: auto


# Model Architecture
architecture: 'retinanet'
num_classes: 1
nms_thresh: 0.05

# Architecture specific params
retinanet:
    # Non-max supression of overlapping predictions
    score_thresh: 0.1

train:

    csv_file:
    root_dir:

    #Optomizer  initial learning rate
    lr: 0.01

    #Print loss every n epochs
    epochs: 20
    #Useful debugging flag in pytorch lightning, set to True to get a single batch of training to test settings.
    fast_dev_run: False

    #pin images to GPU memory for fast training. This depends on GPU size and number of images.
    preload_images: True

validation:
    #callback args
    csv_file:
    root_dir:
    #Intersection over union evaluation
    iou_threshold: 0.4
    val_accuracy_interval: 5