# A yaml file that contains the configuration for the pipeline
user: 'ben'
server_url: 'serenity.ifas.ufl.edu'
key_filename: '/home/b.weinstein/.ssh/id_rsa.pub'
folder_name: '/pgsql/retrieverdash/everglades-label-studio/everglades-data'
#model_checkpoint: '/blue/ewhite/everglades/Zooniverse//20220910_182547/species_model.pl'
model_checkpoint:
test_csv: '/blue/ewhite/everglades/Zooniverse/cleaned_test/test_resized_no_nan.csv'
images_to_annotate_dir: '/blue/ewhite/everglades/label_studio/images_to_annotate'
checkpoint_dir: '/blue/ewhite/everglades/Zooniverse/'
train_dir: '/blue/ewhite/everglades/Zooniverse/'
annotated_images_dir: '/blue/ewhite/everglades/label_studio/annotated_images'
annotation_csv: /blue/ewhite/everglades/label_studio/annotated_images/train_20231214_093907.csv